[package]
name = "cic2nf"
version = "0.3.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["cargo", "wrap_help"] }
csv = "1.4.0"
env_logger = "0.11.8"
glob = "0.3.3"
itertools = "0.14.0"
log = "0.4.29"
